#
# Module manifest for module 'PSGet_Save-SpotlightImages'
#
# Generated by: robertlarue
#
# Generated on: 6/9/2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Save-SpotlightImages'

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'c31a181c-59e8-49cc-8e72-19a18a7f647e'

# Author of this module
Author = 'robertlarue'

# Company or vendor of this module
CompanyName = 'la-rue.com'

# Copyright statement for this module
Copyright = '(c) 2021 robertlarue. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Saves spotlight images from the Windows lock screen to a user''s Pictures folder'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Save-SpotlightImages'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Save','Spotlight','Image','Lock','Screen','Desktop','Pictures'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/robertlarue/Save-SpotlightImages/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/robertlarue/Save-SpotlightImages'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'

Save-SpotlightImages

Saves spotlight images from the Windows lock screen to a user''s Pictures folder.

Images shown on the Windows lock screen are located in the AppData\Local\Packages\Microsoft.Windows.ContentDeliveryManager_cw5n1h2txyewy\LocalState\Assets folder.
This utilty will save them to a user''s Pictures folder or any other destination.
By default it only saves images in the landscape orientation.

Script Help
-----------

<#
.Synopsis
    This function saves images from the Windows lock screen to a user''s Pictures folder
.Description
    Saves spotlight images from the Windows lock screen
.Example
    Save-SpotlightImages
    Error Skipped AlreadyPresent Copied
    ----- ------- -------------- ------
        0       4              0      4
.Parameter IncludePortrait
    By default, only images in landscape orientation are saved. With this flag, all images are saved including those in portrait orientation.
.Parameter Destination
    By default, images are saved to ~\Pictures\LogonImages. With this parameter, an alternate destination can be specified.
#>


Version History:
---------------
V1.0
> Initial release to the PowerShell Gallery
'@

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

